source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'page-object'
gem 'rake'
gem 'rspec-expectations'
gem 'pretty_face'
gem 'multi_test'
gem 'watir-webdriver'
gem 'selenium-webdriver', "3.3.0"
gem 'bundler'
gem 'data_magic'
gem 'require_all'
gem 'fig_newton'
gem 'simplecov', '=0.7'
gem 'gherkin', '~>4.0'
gem 'json','>=1.8.2'
gem 'net-http-persistent', '~> 2.9.4'
#gem install 'term-ansicolor'
# gem 'persistent', '~> 0.1.0'
gem 'uuid'
gem 'pry'
#gem 'yaml'